server:
  port: 8201
  servlet:
    contextPath: /api
  tomcat:
    max-threads: 400

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  profiles:
    active: dev
  application:
    name: blog-application
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use-jdbc-metadata-defaults: false

    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  hateoas:
    use-hal-as-default-json-media-type: false